resetColors
resetColors
	theme resetColors.
	
	backgroundColor := theme backgroundColor.
	backgroundColorMorph color: backgroundColor .
	
	borderColor := theme borderColor.
	borderColorMorph color: borderColor .
	
	buttonColor := theme buttonColor.
	buttonColorMorph color: buttonColor .
	
	textColor := theme textColor.
	textColorMorph color: textColor .
	
	scrollbarColor := theme scrollbarColor.
	scrollbarColorMorph color: scrollbarColor .
	
	windowColor   := theme windowColor.
	windowColorMorph color: windowColor .
	